apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::948504086097:role/eksctl-dj-starsim-nodegroup-ng-bb6-NodeInstanceRole-5yqWnytzFCSi
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::948504086097:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2024-08-06T05:14:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1454"
  uid: e133ab04-c78c-4555-903c-93dbf2a84d6a
